### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by Somebi** [webRTC-io/webRTC.io#13]
Could you please update your demo?

**Comment by ryanleland** [comment]
+1

**Comment by aeosynth** [comment]
:+1:

**Comment by coreybutler** [comment]
+1

**Comment by benbrittain** [comment]
all right guys... I'm on it!

**Comment by benbrittain** [comment]
Done!

**Comment by Somebi** [comment]
Still not working for me. :)
Have you updated the link in the readme?

**Comment by dennismartensson** [comment]
There is a demo up on this address. http://webrtc.dennis.is/

**Comment by dennismartensson** [comment]
I will commit the code changes and the change the link later today

**Comment by Somebi** [comment]
Thank you.

**Comment by aeosynth** [comment]
The link in the readme - http://bit.ly/webrtcio - does not work; the link posted here - http://webrtc.dennis.is/ - does
